// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace BomberosAPI.AcceptanceTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AutenticacionYControlDeAccesoPorRolesUS_12US_34US_41Feature : object, Xunit.IClassFixture<AutenticacionYControlDeAccesoPorRolesUS_12US_34US_41Feature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("es"), "Features", "Autenticación y control de acceso por roles (US-12, US-34, US-41)", @"  Como usuario del sistema SMAB (Jefe de Bomberos, Personal Médico, Bombero Aspirante)
  Quiero autenticarme con mis credenciales
  Para acceder a las funcionalidades autorizadas según mi rol

  Criterio de aceptación:
  - Se debe validar el correo y contraseña contra la base de datos.
  - Al autenticarse correctamente, el sistema responde 200 OK con un token JWT firmado y la lista de roles del usuario.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "01_Login.feature"
#line hidden
        
        public AutenticacionYControlDeAccesoPorRolesUS_12US_34US_41Feature(AutenticacionYControlDeAccesoPorRolesUS_12US_34US_41Feature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Inicio de sesión exitoso por rol")]
        [Xunit.TraitAttribute("FeatureTitle", "Autenticación y control de acceso por roles (US-12, US-34, US-41)")]
        [Xunit.TraitAttribute("Description", "Inicio de sesión exitoso por rol")]
        [Xunit.TraitAttribute("Category", "acceptance")]
        [Xunit.TraitAttribute("Category", "auth")]
        [Xunit.InlineDataAttribute("Fire Chief", "jefe@smab.app", "Smab2026!", "FIRE_CHIEF", new string[0])]
        [Xunit.InlineDataAttribute("Medical", "medico@smab.app", "Smab2026!", "MEDICAL", new string[0])]
        [Xunit.InlineDataAttribute("Firefighter Trainee", "bombero@smab.app", "Smab2026!", "FIREFIGHTER_TRAINEE", new string[0])]
        public async global::System.Threading.Tasks.Task InicioDeSesionExitosoPorRol(string rolDescription, string email, string password, string roleCode, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "acceptance",
                    "auth"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("RolDescription", rolDescription);
            argumentsOfScenario.Add("Email", email);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("RoleCode", roleCode);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Inicio de sesión exitoso por rol", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 13
    await testRunner.GivenAsync(string.Format("que existe un usuario registrado con correo \"{0}\" y contraseña \"{1}\" con rol \"{2}" +
                            "\"", email, password, roleCode), ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 14
    await testRunner.WhenAsync(string.Format("el usuario envía una solicitud de inicio de sesión con correo \"{0}\" y contraseña " +
                            "\"{1}\"", email, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 15
    await testRunner.ThenAsync("la respuesta de autenticación debe tener código de estado 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 16
    await testRunner.AndAsync("la respuesta debe contener un token JWT válido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 17
    await testRunner.AndAsync(string.Format("el perfil del usuario autenticado debe incluir el rol \"{0}\"", roleCode), ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await AutenticacionYControlDeAccesoPorRolesUS_12US_34US_41Feature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await AutenticacionYControlDeAccesoPorRolesUS_12US_34US_41Feature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
