// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace BomberosAPI.AcceptanceTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CreacionDeSesionDeEntrenamientoYGestionDeParticipantesUS_12US_27Feature : object, Xunit.IClassFixture<CreacionDeSesionDeEntrenamientoYGestionDeParticipantesUS_12US_27Feature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("es"), "Features", "Creación de sesión de entrenamiento y gestión de participantes (US-12, US-27)", @"  Como Jefe de Bomberos (chief-001)
  Quiero crear una nueva sesión de entrenamiento en la casa de fuego, asignar personal médico/capacitadores y enviar invitaciones a aspirantes
  Para organizar y planificar las prácticas de entrenamiento con control de participantes

  Criterio de aceptación (Tabla 9.1):
  - El Jefe de Bomberos crea la sesión especificando nombre, fecha, lugar (Burn House) y capacidad de quemas.
  - Se asigna personal médico y capacitadores.
  - Se agregan bomberos aspirantes enviándoles invitaciones por correo electrónico.
  - La sesión se crea con sus participantes y las invitaciones quedan en estado Pendiente.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "02_CrearSesionEntrenamiento.feature"
#line hidden
        
        public CreacionDeSesionDeEntrenamientoYGestionDeParticipantesUS_12US_27Feature(CreacionDeSesionDeEntrenamientoYGestionDeParticipantesUS_12US_27Feature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="El Jefe de Bomberos crea exitosamente una sesión de entrenamiento con participant" +
            "es e invitaciones")]
        [Xunit.TraitAttribute("FeatureTitle", "Creación de sesión de entrenamiento y gestión de participantes (US-12, US-27)")]
        [Xunit.TraitAttribute("Description", "El Jefe de Bomberos crea exitosamente una sesión de entrenamiento con participant" +
            "es e invitaciones")]
        [Xunit.TraitAttribute("Category", "acceptance")]
        [Xunit.TraitAttribute("Category", "training_sessions")]
        public async global::System.Threading.Tasks.Task ElJefeDeBomberosCreaExitosamenteUnaSesionDeEntrenamientoConParticipantesEInvitaciones()
        {
            string[] tagsOfScenario = new string[] {
                    "acceptance",
                    "training_sessions"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("El Jefe de Bomberos crea exitosamente una sesión de entrenamiento con participant" +
                    "es e invitaciones", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
    await testRunner.GivenAsync("que el usuario \"chief-001\" con correo \"jefe@smab.app\" ha iniciado sesión como \"FI" +
                        "RE_CHIEF\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Titulo",
                            "Tipo",
                            "Ubicacion",
                            "CapacidadPlanificada",
                            "DiasEnElFuturo"});
                table1.AddRow(new string[] {
                            "Capacitación Quemas Vivas - Casa de Fuego Alpha",
                            "Live Fire Training",
                            "Casa de Fuego (Burn House)",
                            "12",
                            "5"});
#line 16
    await testRunner.WhenAsync("el Jefe de Bomberos crea una sesión de entrenamiento con los siguientes datos:", ((string)(null)), table1, "Cuando ");
#line hidden
#line 19
    await testRunner.ThenAsync("la respuesta debe tener código de estado 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 20
    await testRunner.AndAsync("la sesión de entrenamiento creada debe tener estado \"Scheduled\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 21
    await testRunner.WhenAsync("el Jefe de Bomberos asigna al personal médico \"medico@smab.app\" a la sesión", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 22
    await testRunner.AndAsync("el Jefe de Bomberos envía una invitación por correo al bombero aspirante \"bombero" +
                        "@smab.app\" para la sesión", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 23
    await testRunner.AndAsync("el Jefe de Bomberos envía una invitación por correo al bombero aspirante \"bombero" +
                        "2@smab.app\" para la sesión", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 24
    await testRunner.ThenAsync("las invitaciones para la sesión son creadas exitosamente con estado \"Pending\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CreacionDeSesionDeEntrenamientoYGestionDeParticipantesUS_12US_27Feature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CreacionDeSesionDeEntrenamientoYGestionDeParticipantesUS_12US_27Feature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
