// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace BomberosAPI.AcceptanceTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class RegistroYValidacionFisiologicaDeSignosVitalesUS_34US_36Feature : object, Xunit.IClassFixture<RegistroYValidacionFisiologicaDeSignosVitalesUS_34US_36Feature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("es"), "Features", "Registro y validación fisiológica de signos vitales (US-34, US-36)", @"  Como Personal Médico / Nutricionista (medical-001)
  Quiero registrar las mediciones de signos vitales de un bombero aspirante durante una sesión
  Para validar los rangos fisiológicos y asociar las mediciones al historial clínico del aspirante

  Criterio de aceptación (Tabla 9.1):
  - El personal médico registra frecuencia cardíaca, saturación de oxígeno SpO2, presión arterial, temperatura corporal y rol en la práctica.
  - El sistema valida las mediciones contra sus rangos fisiológicos permitidos.
  - Las mediciones válidas se vinculan al participante y quedan disponibles para consulta médica y diagramas interactivos.
  - Mediciones fuera de rangos fisiológicos son rechazadas con error 400 Bad Request.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "03_RegistrarSignosVitales.feature"
#line hidden
        
        public RegistroYValidacionFisiologicaDeSignosVitalesUS_34US_36Feature(RegistroYValidacionFisiologicaDeSignosVitalesUS_34US_36Feature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Registro exitoso de signos vitales dentro de rangos fisiológicos")]
        [Xunit.TraitAttribute("FeatureTitle", "Registro y validación fisiológica de signos vitales (US-34, US-36)")]
        [Xunit.TraitAttribute("Description", "Registro exitoso de signos vitales dentro de rangos fisiológicos")]
        [Xunit.TraitAttribute("Category", "acceptance")]
        [Xunit.TraitAttribute("Category", "vital_signs")]
        public async global::System.Threading.Tasks.Task RegistroExitosoDeSignosVitalesDentroDeRangosFisiologicos()
        {
            string[] tagsOfScenario = new string[] {
                    "acceptance",
                    "vital_signs"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registro exitoso de signos vitales dentro de rangos fisiológicos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
    await testRunner.GivenAsync("que existe una sesión de entrenamiento activa con el aspirante \"bombero@smab.app\"" +
                        " como participante registrado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 16
    await testRunner.AndAsync("el usuario \"medical-001\" con correo \"medico@smab.app\" ha iniciado sesión como \"ME" +
                        "DICAL\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "FrecuenciaCardiaca",
                            "PresionSistolica",
                            "PresionDiastolica",
                            "Temperatura",
                            "SaturacionOxigeno",
                            "RolPractica",
                            "EsFumador",
                            "ExpuestoHumo48h"});
                table2.AddRow(new string[] {
                            "78",
                            "120",
                            "80",
                            "36.6",
                            "98",
                            "Pitonero",
                            "false",
                            "false"});
#line 17
    await testRunner.WhenAsync("el médico registra una medición de signos vitales para el aspirante con los sigui" +
                        "entes valores:", ((string)(null)), table2, "Cuando ");
#line hidden
#line 20
    await testRunner.ThenAsync("la respuesta debe tener código de estado 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 21
    await testRunner.AndAsync("la medición de signos vitales queda registrada y vinculada al participante de la " +
                        "sesión", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Rechazo de medición de signos vitales fuera de rangos fisiológicos razonables")]
        [Xunit.TraitAttribute("FeatureTitle", "Registro y validación fisiológica de signos vitales (US-34, US-36)")]
        [Xunit.TraitAttribute("Description", "Rechazo de medición de signos vitales fuera de rangos fisiológicos razonables")]
        [Xunit.TraitAttribute("Category", "acceptance")]
        [Xunit.TraitAttribute("Category", "vital_signs")]
        [Xunit.TraitAttribute("Category", "validation")]
        public async global::System.Threading.Tasks.Task RechazoDeMedicionDeSignosVitalesFueraDeRangosFisiologicosRazonables()
        {
            string[] tagsOfScenario = new string[] {
                    "acceptance",
                    "vital_signs",
                    "validation"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Rechazo de medición de signos vitales fuera de rangos fisiológicos razonables", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 25
    await testRunner.GivenAsync("que existe una sesión de entrenamiento activa con el aspirante \"bombero@smab.app\"" +
                        " como participante registrado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 26
    await testRunner.AndAsync("el usuario \"medical-001\" con correo \"medico@smab.app\" ha iniciado sesión como \"ME" +
                        "DICAL\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "FrecuenciaCardiaca",
                            "PresionSistolica",
                            "PresionDiastolica",
                            "Temperatura",
                            "SaturacionOxigeno"});
                table3.AddRow(new string[] {
                            "450",
                            "350",
                            "200",
                            "65.0",
                            "150"});
#line 27
    await testRunner.WhenAsync("el médico intenta registrar signos vitales con valores fisiológicamente inválidos" +
                        ":", ((string)(null)), table3, "Cuando ");
#line hidden
#line 30
    await testRunner.ThenAsync("la respuesta debe tener código de estado 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 31
    await testRunner.AndAsync("la respuesta debe indicar errores de validación en los rangos fisiológicos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await RegistroYValidacionFisiologicaDeSignosVitalesUS_34US_36Feature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await RegistroYValidacionFisiologicaDeSignosVitalesUS_34US_36Feature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
