// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace BomberosAPI.AcceptanceTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ConsultaDeResultadosPropiosYProteccionDePrivacidadUS_41US_45Feature : object, Xunit.IClassFixture<ConsultaDeResultadosPropiosYProteccionDePrivacidadUS_41US_45Feature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("es"), "Features", "Consulta de resultados propios y protección de privacidad (US-41, US-45)", @"  Como Bombero Aspirante (trainee-001)
  Quiero iniciar sesión y consultar exclusivamente mis resultados de sesión y mi historial de signos vitales
  Para monitorear mi rendimiento y evolución médica sin acceder a datos de otros aspirantes

  Criterio de aceptación (Tabla 9.1):
  - El aspirante inicia sesión con sus credenciales.
  - Al consultar su historial de signos vitales (/api/vital-signs/by-trainee/{id}), visualiza únicamente sus propias lecturas históricas.
  - Al consultar resultados de sus sesiones (/api/session-results/by-participant/{id}), recibe su información respectiva.
  - El sistema no permite que un aspirante acceda a lecturas médicas no filtradas o de otros aspirantes (403 Forbidden o filtrado estricto).", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "04_ConsultarResultadosPropios.feature"
#line hidden
        
        public ConsultaDeResultadosPropiosYProteccionDePrivacidadUS_41US_45Feature(ConsultaDeResultadosPropiosYProteccionDePrivacidadUS_41US_45Feature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="El bombero aspirante consulta sus propios resultados de sesión e historial de sig" +
            "nos vitales")]
        [Xunit.TraitAttribute("FeatureTitle", "Consulta de resultados propios y protección de privacidad (US-41, US-45)")]
        [Xunit.TraitAttribute("Description", "El bombero aspirante consulta sus propios resultados de sesión e historial de sig" +
            "nos vitales")]
        [Xunit.TraitAttribute("Category", "acceptance")]
        [Xunit.TraitAttribute("Category", "trainee_results")]
        public async global::System.Threading.Tasks.Task ElBomberoAspiranteConsultaSusPropiosResultadosDeSesionEHistorialDeSignosVitales()
        {
            string[] tagsOfScenario = new string[] {
                    "acceptance",
                    "trainee_results"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("El bombero aspirante consulta sus propios resultados de sesión e historial de sig" +
                    "nos vitales", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
    await testRunner.GivenAsync("que existen mediciones de signos vitales registradas para el aspirante \"bombero@s" +
                        "mab.app\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 16
    await testRunner.AndAsync("existen mediciones de signos vitales registradas para otro aspirante \"bombero2@sm" +
                        "ab.app\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 17
    await testRunner.WhenAsync("el usuario \"trainee-001\" con correo \"bombero@smab.app\" ha iniciado sesión como \"F" +
                        "IREFIGHTER_TRAINEE\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 18
    await testRunner.AndAsync("el aspirante consulta su propio historial de signos vitales", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 19
    await testRunner.ThenAsync("la respuesta debe tener código de estado 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 20
    await testRunner.AndAsync("todas las lecturas de signos vitales devueltas deben corresponder únicamente al a" +
                        "spirante \"bombero@smab.app\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 21
    await testRunner.AndAsync("ninguna lectura debe pertenecer al aspirante \"bombero2@smab.app\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="El bombero aspirante tiene restringido el acceso a la lista global de mediciones " +
            "médicas")]
        [Xunit.TraitAttribute("FeatureTitle", "Consulta de resultados propios y protección de privacidad (US-41, US-45)")]
        [Xunit.TraitAttribute("Description", "El bombero aspirante tiene restringido el acceso a la lista global de mediciones " +
            "médicas")]
        [Xunit.TraitAttribute("Category", "acceptance")]
        [Xunit.TraitAttribute("Category", "trainee_results")]
        [Xunit.TraitAttribute("Category", "security")]
        public async global::System.Threading.Tasks.Task ElBomberoAspiranteTieneRestringidoElAccesoALaListaGlobalDeMedicionesMedicas()
        {
            string[] tagsOfScenario = new string[] {
                    "acceptance",
                    "trainee_results",
                    "security"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("El bombero aspirante tiene restringido el acceso a la lista global de mediciones " +
                    "médicas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 25
    await testRunner.GivenAsync("que el usuario \"trainee-001\" con correo \"bombero@smab.app\" ha iniciado sesión com" +
                        "o \"FIREFIGHTER_TRAINEE\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 26
    await testRunner.WhenAsync("el aspirante intenta consultar el listado global no filtrado de signos vitales", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 27
    await testRunner.ThenAsync("la respuesta debe tener código de estado 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ConsultaDeResultadosPropiosYProteccionDePrivacidadUS_41US_45Feature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ConsultaDeResultadosPropiosYProteccionDePrivacidadUS_41US_45Feature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
